name: ad-sc
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - scanpy=1.10.*
  - anndata
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - leidenalg
  - python-igraph
